### PR TITLE
Makefile: Auto detect wheather using clang or gcc

### PR DESCRIPTION
**Pull request by corona10**
While I am testing the mir on my local machine. 
I should choose $CC by modifying Makefile but this work is repetitive.
This PR is not perfect work but resolves most of the situations during development.

### CODE REVIEW

**Comment by rofl0r** [comment]
you can use `make CC="clang -whatever"` to override the default setting.

**Comment by corona10** [comment]
@rofl0r 

> you can use make CC="clang -whatever" to override the default setting.

Thanks for the comment.
1. Your suggestion can be one of the solutions.
2. IMHO, this PR makes the user not to care about $CC and don't have to set value for executing something. I think that people expect to run the makefile without set specific value.
3. This PR also can remove hardcoded value of gcc or clang

**Comment by vnmakarov** [comment]
Thank you.  I've merged your request.  There is some value for the change but I should only say that I did not work on build/configuration of code yet.  The current make file is only for my current work flow.

I am going to use autoconf (may be automake) when I start my work on the release.    I don't like cmake.  This is just my personal preference.

**Comment by corona10** [comment]
@vnmakarov I am looking forward your first relelase :)

**Pull request merged**
