### PR TITLE
Fixing up WIN64 volatile/non-volatile registers handling.

### PR DESCRIPTION
**Pull request by logzero**

### CODE REVIEW

**Comment by vnmakarov** [comment]
Sorry for the delay with my answer.  I was and am still busy with other projects.
Thank you for your pull request.  I've merged it into the repository.

**Comment by vnmakarov** [comment]
> What about using `(mask & (1 << reg))` in such cases?

Sorry, I thought this question for logzero but as he is silent I decide to answer it.
I think it is a micro-optimization.  The current code is fine.  There are lot of performance trouble spots in MIR-generator and all machine-dependent code is nowhere close to them.

**Comment by logzero** [comment]
I didn't feel like it was something for me to decide.

Btw gcc does some fun stuff with
````
return !(hard_reg == BX_HARD_REG || hard_reg == SI_HARD_REG || hard_reg == DI_HARD_REG
            || (hard_reg >= R12_HARD_REG && hard_reg <= R15_HARD_REG)
            || (hard_reg >= XMM6_HARD_REG && hard_reg <= XMM15_HARD_REG));
````
It figures out to use a bitmask, but kind of gives up on it halfway. Probably because it uses bit test instruction:
````
if (hard_reg <= 15) { // gp regs
  if (0xf0c8 & (1 << hard_reg)) // bit test gp regs bitmask
    return 0;
} else { // xmm regs
  hard_reg -= 22;
  return (hard_reg < 9); // xmm6 - xmm15
}
````

**Comment by logzero** [comment]
Actually GCC does use a 32 bit register bitmask if MIR_reg_t is uint32_t as defined in mir. I've used int for esting, duh.

It generates
````
if (hard_reg > 31) return 1;
return !(0xFFC0F0C8 >> hard_reg) & 1;
````
Which is pretty cool.

**Pull request merged**
